### ISSUE TITLE
eror saat node . 

### ISSUE THREAD

**Issue by kacang123** [mukhlisakbr/node-whatsapp-bot#4]
/home/student_00_760fce952469/node-whatsapp-bot/node_modules/mongoose/lib/connection.js:651
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/home/student_00_760fce952469/node-whatsapp-bot/node_modules/mongoose/lib/connection.js:651:11)
    at Mongoose.connect (/home/student_00_760fce952469/node-whatsapp-bot/node_modules/mongoose/lib/index.js:339:15)
    at Object.<anonymous> (/home/student_00_760fce952469/node-whatsapp-bot/db.js:9:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/student_00_760fce952469/node-whatsapp-bot/messageHandler.js:16:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by nikkixploit** [comment]
> /home/student_00_760fce952469/node-whatsapp-bot/node_modules/mongoose/lib/connection.js:651
> throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
> ^
> 
> MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
> at NativeConnection.Connection.openUri (/home/student_00_760fce952469/node-whatsapp-bot/node_modules/mongoose/lib/connection.js:651:11)
> at Mongoose.connect (/home/student_00_760fce952469/node-whatsapp-bot/node_modules/mongoose/lib/index.js:339:15)
> at Object. (/home/student_00_760fce952469/node-whatsapp-bot/db.js:9:10)
> at Module._compile (internal/modules/cjs/loader.js:689:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:22:18)
> at Object. (/home/student_00_760fce952469/node-whatsapp-bot/messageHandler.js:16:19)
> at Module._compile (internal/modules/cjs/loader.js:689:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Buat file bernama .env
Lalu didalam file tsb isi file dengan ini:
MONGO_URL=mongo-db-url.com

**Comment by Auza39** [comment]
ditaro dimana kak filenya

**Comment by Auza39** [comment]
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (C:\wabot\node_modules\mongoose\lib\connection.js:651:11)
    at Mongoose.connect (C:\wabot\node_modules\mongoose\lib\index.js:339:15)
    at Object.<anonymous> (C:\wabot\db.js:9:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\wabot\messageHandler.js:16:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
